### ISSUE TITLE
Installation fails with jars

### ISSUE THREAD

**Issue by iwkse** [ITDSystems/orgchart#2]
Hi, I went through the process of installation (a clean installation), using the JARs method that is my favourite. When I click in the admin link (org chart) I get this error:

The Web Script /share/service/components/admin/orgchart has responded with a status of 500 - Internal Error.

500 Description:	An error inside the HTTP server which prevented it from fulfilling the request.
 
Message:	06120000 Failed to execute script 'classpath*:alfresco/web-extension/site-webscripts/com/alvexcore/console/orgchart-admin/orgchart-admin.get.js': null
Server:	Spring WebScripts - v6.5.0 schema 1.000
Time:	12-lug-2016 18.48.26
 
Diagnostics:	Inspect Web Script (com/alvexcore/console/orgchart-admin/orgchart-admin.get)

Web Script: com/alvexcore/console/orgchart-admin/orgchart-admin.get
Generated from /share/page/script/com/alvexcore/console/orgchart-admin/orgchart-admin.get on 12-lug-2016 18.58.22
Script Properties
Id:	com/alvexcore/console/orgchart-admin/orgchart-admin.get
Short Name:	Orgchart Configuration
Description:	Configure orgchart
Authentication:	none
Transaction:	none
Method:	GET
URL Template:	/components/admin/orgchart
Format Style:	any
Default Format:	html
Negotiated Formats:	[undefined]
Implementation:	class org.springframework.extensions.webscripts.DeclarativeWebScript
Extensions:	[undefined]
Store: classpath:alfresco/web-extension/site-webscripts

File: com/alvexcore/console/orgchart-admin/orgchart-admin.get.desc.xml
<webscript>
	<shortname>Orgchart Configuration</shortname>
	<description>Configure orgchart</description>
	<url>/components/admin/orgchart</url>
	<family>admin-console</family>
</webscript>
File: com/alvexcore/console/orgchart-admin/orgchart-admin.get.js
<import resource="classpath:/alfresco/web-extension/site-webscripts/com/alvexcore/js/alvex-config.lib.js">

var uiConfig = Alvex.configs.getConfig('orgchart', 'orgchart-view.default');
var syncConfig = Alvex.configs.getConfig('orgchart', 'orgchart-sync.default');

model.config = {
    defaultRoleName: uiConfig.props['alvexoc:defaultRoleName'] ? uiConfig.props['alvexoc:defaultRoleName'] : '',
    uiConfigNodeRef: uiConfig.nodeRef,
    syncConfigNodeRef: syncConfig.nodeRef,
    syncSource: syncConfig.props['alvexoc:syncSource']
}

var conn = remote.connect("alfresco");
var resp = eval('(' + conn.get("/api/alvex/server") + ')');

model.alvexVersion = resp.version;
model.alvexEdition = resp.edition;
model.alvexCodename = resp.codename;
File: com/alvexcore/console/orgchart-admin/orgchart-admin.get.head.ftl
<#include "/form.get.head.ftl">

<@script type="text/javascript" src="${page.url.context}/res/modules/simple-dialog.js" />
<@script type="text/javascript" src="${page.url.context}/res/js/grouped-data-table/grouped-data-table.js" />
<@script type="text/javascript" src="${page.url.context}/res/js/components/alvex/orgchart/people-finder.js" />
<@script type="text/javascript" src="${page.url.context}/res/js/components/alvex/orgchart/orgchart-view.js" />

<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/components/people-finder/people-finder.css" />
<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/css/components/alvex/orgchart/orgchart-view.css" />
<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/css/grouped-data-table/grouped-data-table.css" />
<@link rel="stylesheet" type="text/css" href="${page.url.context}/res/components/profile/profile.css" />
File: com/alvexcore/console/orgchart-admin/orgchart-admin.get.html.ftl

<input id="yui-history-field" type="hidden" />

<#assign htmlId=args.htmlid?js_string>

<script type="text/javascript">
	function showSpoiler(id)
	{
		var inner = document.getElementById("${htmlId}-panel-" + id);
		var button = document.getElementById("${htmlId}-button-" + id);
		if (inner.style.display == "none")
		{
			inner.style.display = "";
			button.value=" - ";
		}
		else
		{
			inner.style.display = "none";
			button.value=" + ";
		}
		YAHOO.Bubbling.fire("formVisibilityChanged");
	}
</script>

<div id="${htmlId}-body" class="orgchart-admin">
	<div class="title set-bordered-panel-heading">
		<span><input id="${htmlId}-button-1" class="btn" type="button" onclick="showSpoiler(1);" value=" + " /></span>
		<label>${msg("alvex.orgchart.majorParameters")}</label>
	</div>
	<div id="${htmlId}-panel-1" class="set-bordered-panel-body" style="display:none;">
		<div style="padding-bottom: 1em;">
			<div class="label" style="float: left;">${msg("alvex.orgchart.configureUI.header")}:</div>
			<div style="padding-left: 15em;">
				<span>
					
					<div>
						<span class="yui-button yui-push-button" id="${htmlId}-ui-config">
							<span class="first-child">
								<button>${msg("alvex.orgchart.configureUI")}</button>
							</span>
						</span>
					</div>
				</span>
			</div>
		</div>
		<#if alvexEdition == 'Enterprise' >
		<div style="padding-bottom: 1em;">
			<div class="label" style="float: left;">${msg("alvex.orgchart.syncParameters")}:</div>
			<div style="padding-left: 15em;">
				<span>
					
					<div style="float:left;">
						<span class="yui-button yui-push-button" id="${htmlId}-sync-config">
							<span class="first-child">
								<button>${msg("alvex.orgchart.configureSync")}</button>
							</span>
						</span>
					</div>
				</span>
				<span>
					
					<div>
						<span class="yui-button yui-push-button" id="${htmlId}-sync-now">
							<span class="first-child">
								<button>${msg("alvex.orgchart.syncNow")}</button>
							</span>
						</span>
					</div>
				</span>
			</div>
		</div>
		</#if>
	</div>
	<hr style="margin-top: 15px; margin-bottom: 15px;"/>
	<div class="title set-bordered-panel-heading">
		<span><input id="${htmlId}-button-2" class="btn" type="button" onclick="showSpoiler(2);" value=" + " /></span>
		<label>${msg("alvex.orgchart.configureRoles.header")}</label>
	</div>
	<div id="${htmlId}-panel-2" class="set-bordered-panel-body" style="display:none;">
		<div id="${htmlId}-roles">
			<span>
					
					<div>
						<span class="yui-button yui-push-button" id="${htmlId}-add-role">
							<span class="first-child">
								<button>${msg("alvex.orgchart.addRole")}</button>
							</span>
						</span>
					</div>
			</span>
		</div>
		<div id="${htmlId}-roles-table"></div>
	</div>
	<hr style="margin-top: 15px; margin-bottom: 15px;"/>
	<div class="title set-bordered-panel-heading">
		<span><input id="${htmlId}-button-3" class="btn" type="button" onclick="showSpoiler(3);" value=" - " /></span>
		<label>${msg("alvex.orgchart.configureUnits.header")}</label>
	</div>
	<div id="${htmlId}-panel-3" class="set-bordered-panel-body">
		<div id="${htmlId}-page-tree-view"></div>
	</div>
</div>

<#assign controlId = htmlId + "-cntrl">

<#assign pickerId = controlId + "-picker">

<div id="${pickerId}" class="picker yui-panel hidden">

	<div id="${pickerId}-head" class="hd"></div>
	<div id="${pickerId}-body" class="bd">
		<div id="${pickerId}-container">

			<div id="doc">

				<div class="yui-g orgchart-picker-menu">
					<div id="${pickerId}-view-selector" class="yui-u first yui-skin-sam picker-view-selector">
						<strong>${msg("alvex.orgchart.show_by")} </strong>
						<span id="${pickerId}-view-roles">${msg("alvex.orgchart.show_by_role")}</span>
						<span id="${pickerId}-view-people">${msg("alvex.orgchart.show_by_name")}</span>
					</div>
					<#if config.syncSource == 'none' >
					<div class="yui-u yui-skin-sam" style="padding-top: 0.7em; cursor: pointer;">
						<span id="${pickerId}-add-users">${msg("alvex.orgchart.add_users")}</span>
					</div>
					</#if>
				</div>

				<div class="yui-g">
					<div id="${pickerId}-dataTable" class="yui-u first yui-skin-sam picker-part">
						<div class="people-table">
							<div id="${pickerId}-group-members"></div>
						</div>
					</div>
					<div id="${pickerId}-userDetails" class="yui-u" yui-skin-sam picker-part>
						<div id="${pickerId}-person-info" class="profile">
							<div>
								<div class="photo">
									<img id="${pickerId}-person-img" class="photoimg"></img>
								</div>
								<div class="namelabelcustom" id="${pickerId}-person-name"></div>
								<div class="fieldlabel" id="${pickerId}-person-title"></div>
								<div class="fieldlabel" id="${pickerId}-person-company"></div>
							</div>
							<div class="row">
								<span class="labelcustom">${msg("alvex.orgchart.telephone")}</span>
								<span class="valuecustom" id="${pickerId}-person-telephone"></span>
							</div>
							<div class="row">
								<span class="labelcustom">${msg("alvex.orgchart.mobile")}</span>
								<span class="valuecustom" id="${pickerId}-person-mobile"></span>
							</div>
							<div class="row">
								<span class="labelcustom">${msg("alvex.orgchart.email")}</span>
								<span class="valuecustom" id="${pickerId}-person-email"></span>
							</div>
							<div class="row">
								<span class="labelcustom">${msg("alvex.orgchart.skype")}</span>
								<span class="valuecustom" id="${pickerId}-person-skype"></span>
							</div>
							<div class="row">
								<span class="labelcustom">${msg("alvex.orgchart.im")}</span>
								<span class="valuecustom" id="${pickerId}-person-im"></span>
							</div>
							
							<div>
								<br/>
								<div id="${pickerId}-person-links"></div>
							</div>
							<hr/>
							<div class="sectionlabelcustom">${msg("alvex.orgchart.person_bio")}</div>
							<div>
								<div id="${pickerId}-person-bio"></div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="bdft">
					&nbsp;
				</div>
				
			</div>
		</div>
	</div>
</div>

<div id="${htmlId}-peoplepicker" class="groups people-picker" style="visibility: hidden;">
	<div class="hd"><span id="${htmlId}-peoplepicker-title">${msg("alvex.orgchart.add_users")}</span></div>
	<div class="bd">
		<div style="margin: auto 10px;">
			<div id="${htmlId}-search-peoplefinder"></div>
		</div>
	</div>
</div>

<#assign addRoleDialogId = controlId + "-add-role-dialog">

<div id="${addRoleDialogId}" class="picker yui-panel add-role-dialog hidden">
	<div id="${addRoleDialogId}-head" class="hd">${msg("alvex.orgchart.addRole")}</div>
	<div id="${addRoleDialogId}-body" class="bd">
		<div><input id="${addRoleDialogId}-role-fixed-name" type="hidden"/></div>
		<div><input id="${addRoleDialogId}-role-old-name" type="hidden"/></div>
		<div>
			<label for="${addRoleDialogId}-role-name">${msg("alvex.orgchart.roleName")}</label>
			<div><input id="${addRoleDialogId}-role-name" type="text"/></div>
		</div>
		<div>
			<label for="${addRoleDialogId}-role-weight">${msg("alvex.orgchart.roleWeight")}</label>
			<div><input id="${addRoleDialogId}-role-weight" type="text"/></div>
		</div>
	</div>
	<div class="ft">
		<input id="${addRoleDialogId}-ok" name="-" type="button" value="${msg("alvex.orgchart.popup_submit_button")}" />
		<input id="${addRoleDialogId}-cancel" name="-" type="button" value="${msg("alvex.orgchart.popup_cancel_button")}" />
	</div>
</div>

<#assign userRolesDialogId = controlId + "-user-roles-dialog">

<div id="${userRolesDialogId}" class="picker yui-panel user-roles-dialog hidden">
	<div id="${userRolesDialogId}-head" class="hd">${msg("alvex.orgchart.userRoles")}</div>
	<div id="${userRolesDialogId}-body" class="bd">
		<div class="hidden">
			<input type="checkbox" name="-" id="${userRolesDialogId}-checkbox" class="formsCheckBox"/>
			<label for="${userRolesDialogId}-checkbox" class="checkbox">Role</label>
		</div>
	</div>
	<div class="ft">
		<input id="${userRolesDialogId}-ok" name="-" type="button" value="${msg("alvex.orgchart.popup_submit_button")}" />
		<input id="${userRolesDialogId}-cancel" name="-" type="button" value="${msg("alvex.orgchart.popup_cancel_button")}" />
	</div>
</div>

<#assign unitRolesDialogId = controlId + "-unit-roles-dialog">

<div id="${unitRolesDialogId}" class="picker yui-panel unit-roles-dialog hidden">
	<div id="${unitRolesDialogId}-head" class="hd">${msg("alvex.orgchart.unitRoles")}</div>
	<div id="${unitRolesDialogId}-body" class="bd">
		<div class="hidden">
			<input type="checkbox" name="-" id="${unitRolesDialogId}-checkbox" class="formsCheckBox"/>
			<label for="${unitRolesDialogId}-checkbox" class="checkbox">Role</label>
		</div>
	</div>
	<div class="ft">
		<input id="${unitRolesDialogId}-ok" name="-" type="button" value="${msg("alvex.orgchart.popup_submit_button")}" />
		<input id="${unitRolesDialogId}-cancel" name="-" type="button" value="${msg("alvex.orgchart.popup_cancel_button")}" />
	</div>
</div>

<script type="text/javascript">//<![CDATA[
	new Alvex.OrgchartViewer("${htmlId}").setOptions({
		mode: "admin",
		defaultRoleName: "${config.defaultRoleName}",
		uiConfigNodeRef: "${config.uiConfigNodeRef}",
		syncConfigNodeRef: "${config.syncConfigNodeRef}",
		syncSource: "${config.syncSource}"
	}).setMessages(
		${messages}
	);
//]]></script>
Store: classpath:alfresco/site-webscripts

[No implementation files]
Store: classpath:surf/webscripts

[No implementation files]
Store: classpath:webscripts

[No implementation files]

**Comment by aviriel** [comment]
Looks strange. What Alfresco version do you use? Any longer trace for this error?

Also please try to install orgchart from https://github.com/ITDSystems/alvex-orgchart (or via https://github.com/ITDSystems/alvex-meta), this repo will be deleted, we move the code to that repo to configure maven so different Alvex components can work independently as well as all together.

**Comment by aviriel** [comment]
Just checked alvex-orgchart current build on Alfresco 2016.05 - org chart in admin console opens without any errors. I have some problems with building JARs (developers told me that it will be fixed asap), but AMPs work excellent.

**Comment by iwkse** [comment]
Hi Airiel! Hope you're doing fine and thanks for your reply. I've tried with latest vanilla alfresco (same as you tried) but with JARs. They build fine but it shows up the error I mentioned above. I will try with the new repository but I didn't try the AMP way, even if I was almost sure it would work. Just it could be great if also with JARs it's fine.
Thanks for your awesome job
Regards

**Comment by aviriel** [comment]
I will try to install JARs as soon as my colleagues fix 
`Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (make-installable-jar) on project orgchart: Unable to parse configuration of mojo org.apache.maven.plugins:maven-assembly-plugin:2.4:single for parameter descriptorRefs: Cannot assign configuration entry 'descriptorRefs' with value 'repo' of type java.lang.String to property of type java.lang.String[] -> [Help 1]`
Sorry :)

**Comment by ArgentumHeart** [comment]
Hi! I fixed the problem in this rep. You can use both JAR and AMP approach.
Fix for alvex-meta will come soon.

**Comment by iwkse** [comment]
Hi! Awesome, I've just tested it and it's working great. I'm closing this bug!
Thanks a lot guys

**Comment by iwkse** [comment]
Hi,
there seems to be another issue with

http://localhost:8080/share/page/alvex-orgchart

It seems like the classpath is not right here as well
./src/main/amp/config/alfresco/web-extension/site-webscripts/components/orgchart-tree-view/orgchart-tree-view.get.js

but this is seems not be not as easy fix as the previous

Regards!

**Comment by ArgentumHeart** [comment]
Hi, seems like issue was the same, try to install now.

**Comment by iwkse** [comment]
Hi, I don't see new commits. I applied the same change as your previous fix, removing the slash, but it doesn't solve the issue, it raises other errors.

**Comment by ArgentumHeart** [comment]
Ok, i need some info in order to reproduce same behaviour. I removed / in the https://github.com/ITDSystems/orgchart rep and created the same pull request for the https://github.com/ITDSystems/alvex-orgchart rep and after that orgchart page is fine for me (http://localhost:8080/share/page/alvex-orgchart). Can you provide more details?

**Comment by iwkse** [comment]
That was a cache issue, I tried again and worked, I don't get the previous error but File not found: /share/res/jit/jit-yc.js

**Comment by iwkse** [comment]
I'm closing this bug as being on a repo that will be deleted. I tried with the new one and it's going okey.

Thanks to all!
